Wal 59 port bookie common message component
PBSA/peerplays-core-gui pull request #37
Opened 2019-02-01 19:30 UTC by aametzler

2019-02-04 15:23 UTC, mseaward requested changes

2019-02-04 15:23 UTC, mseaward commented on src/store/configureStore.dev.js
> +    // Option for immutable
the commented code, are they needed here? If not, remove.

2019-02-04 15:23 UTC, mseaward commented on src/store/configureStore.dev.js
> +//import * as actionCreators from '../actions/CommonMessageActions';
if not used, remove.

2019-02-04 15:23 UTC, mseaward commented on src/reducers/CommonMessageReducer.js
> +  sideBarMessages: [],
`sidebar` would make more sense being renamed `aside`.

2019-02-04 15:23 UTC, mseaward commented on src/reducers/CommonMessageReducer.js
> +      const newExchangeMsgState = state.get('headerMessages')
`newHeaderMsgState`

2019-02-04 15:23 UTC, mseaward commented on src/reducers/CommonMessageReducer.js
> +      const newsideBarMessagestate = state.get('sideBarMessages')
const `newAsideMessagestate` = state.get('asideMessages')

These changes might require changes elsewhere in the implementation of this component.

2019-02-04 15:23 UTC, mseaward commented on src/reducers/CommonMessageReducer.js
> +          return mID === 's' + id;
// Filter aside messages.
return mID === 'a' + id;

2019-02-04 15:23 UTC, mseaward commented on src/reducers/CommonMessageReducer.js
> +      return state.set('headerMessages', newExchangeMsgState)
return state.set('headerMessages', newHeaderMsgState)
        .set('asideMessages', newAsideMessagestate)
        .set('messageCount', newMessageCount)
        .set('activeMessage', false);

2019-02-04 15:34 UTC, mseaward commented
Move style sheet for the CommonMessage component into its own directory similarly to BookiePro.

2019-02-05 19:40 UTC, mseaward commented on src/components/CommonMessage/CommonMessage.jsx
> +import _ from 'lodash';
what are these comments `//added` there for?

2019-02-05 19:40 UTC, mseaward commented on src/components/Dashboard/Balances/BalancesContainer.jsx
> +import CommonMessage from '../../CommonMessage/CommonMessage';
Not sure this level of specificity is required to import CommonMessage with the index.js within its directry.

2019-02-06 17:06 UTC, mseaward submitted a review, later dismissed

2019-02-12 18:42 UTC, mseaward submitted a review, later dismissed

2019-02-13 14:49 UTC, imarquette submitted a review, later dismissed

2019-02-15 14:12 UTC, mseaward commented on src/components/Dashboard/Balances/Balances.jsx
> +    hiddenAssets: state.settings.hiddenAssets,
that comma needs to be killed ;p

2019-02-15 14:12 UTC, mseaward commented on src/components/Dashboard/Balances/Balances.jsx
> +    navigateToDepositWithDraw: NavigateActions.navigateToDepositWithDraw,
same for this comma

2019-02-15 14:13 UTC, mseaward commented on src/components/Header/Header.jsx
> +    current_wallet : state.wallet.currentWallet,
and another 🗡

2019-02-15 14:13 UTC, mseaward requested changes
see my comments, some commas to kill. Otherwise, looks good.

2019-02-15 14:21 UTC, mseaward approved these changes

2019-02-15 17:50 UTC, merged